version: '3'

services:

  backend:
    image: selectilla-back
    build: ./SelectIlLa_Backend
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  frontend:
    image: selectilla-front
    build: ./SelectIlLa_front
    ports:
      - "82:80"
    env_file:
      - /home/nawres/projetPFE/SelectIlLa_front/.env
    networks:
      - app-network
  

volumes:
  selectilla_backend_data:


networks:
  app-network:
    driver: bridge